services:
  - type: web
    name: smart-attendance-api
    runtime: python
    rootDir: smart_attendance_backend/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_BC1xWYptXrc5@ep-frosty-pond-a4jh189q-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        value: SmartAttendance@2025#SecureKey$XYZ
